# Generated by Django 5.2.4 on 2026-03-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
