# Generated by Django 5.2.4 on 2026-03-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_medicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
