# Generated by Django 5.2.4 on 2026-03-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_medicalreport_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='taken',
        ),
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('taken', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.medicine')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('medicine', 'date')},
            },
        ),
    ]
