# Generated by Django 5.2.4 on 2026-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_medicine_taken_medicinelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelog',
            name='date',
            field=models.DateField(),
        ),
    ]
