# Generated by Django 5.2.4 on 2026-03-25 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_medicinelog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('bp_sys', models.IntegerField(blank=True, help_text='Systolic BP (e.g. 120)', null=True)),
                ('bp_dia', models.IntegerField(blank=True, help_text='Diastolic BP (e.g. 80)', null=True)),
                ('sugar', models.IntegerField(blank=True, help_text='Blood Sugar mg/dL', null=True)),
                ('pulse', models.IntegerField(blank=True, help_text='Heart Rate bpm', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Blood Oxygen %', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='core.parent')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
