# Generated by Django 5.2.4 on 2026-03-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vitallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
