# Generated by Django 5.2.4 on 2026-03-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_parent_patient_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
